[package]
name = "optionchain_simulator"
version = "0.0.0"
edition = "2024"
authors = ["Joaquin Bejar <jb@taunais.com>"]
description = "OptionChain-Simulator is a lightweight REST API service that simulates an evolving option chain with every request. It is designed for developers building or testing trading systems, backtesters, and visual tools that depend on option data streams but want to avoid relying on live data feeds."
license = "MIT"
readme = "README.md"
repository = "https://github.com/joaquinbejar/OptionChain-Simulator"
homepage = "https://github.com/joaquinbejar/OptionChain-Simulator"
keywords = ["finance", "options", "trading"]
categories = ["finance", "data-structures"]

[dependencies]
optionstratlib = { path = "../OptionStratLib" }
#optionstratlib = "0.4.3"
tracing = "0.1.41"
rust_decimal = { version = "1.36.0", features = ["maths", "serde"] }
#rust_decimal_macros = "1.36.0"
#serde_json = "1.0.139"
serde = "1.0.218"
itertools = "0.14.0"
uuid = { version = "1.16.0", features = ["v4", "v5", "serde"] }
chrono = { version = "0.4.40", features = ["serde"] }
clickhouse-rs = "1.1.0-alpha.1" 
tokio = "1.44.2"

[workspace]
members = [
    "examples/session",
]

[workspace.dependencies]
optionstratlib = { path = "../OptionStratLib" }
tracing = "0.1.41"
